controller_wbmpc:
  type: loco3d::controller_wbmpc
  dt: 0.0005
  interpolate: false
  controller_dt: 0.0005
  estimator_dt: 0.001
  starting_base_position: [0., 0., 1.2]
  estimated_angular_velocity_scaling_gain: 1.0
  estimated_linear_velocity_scaling_gain: 1.0
  joint_velocity_scaling_gain: 1.0
  global_torque_gain: 1.0
  spawn_controller_thread: true
  spawn_estimator_thread: true
  imu_frame_name: imu_link
  imu_name: base_imu

  estimator_parameters:
    robot_model_chains: [gripper_left_base_link, gripper_right_base_link, left_sole_link, right_sole_link, rgbd_rgb_frame, imu_link]

  contact_estimator: ""
  # config_file_name: 'controller_wbmpc.yaml'